apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ .Release.Name }}-gateway-to-services
  namespace: {{ include "spree-store.namespace" . }}
  labels: {{- include "spree-store.labels" . | nindent 4 }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: {{ .Values.gateway.namespace }}
  to:
    - group: ""
      kind: Service
